title: Ricordi del Nonno
description: Una vita ordinaria in tempi straordinari

url: https://libro-nonno.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/
author:
  name: "Pierluigi Melzani"

# Header Option
# header: large

collections:
  chapters:
    output: true
    permalink: /chapters/:name/

  chapters_en:
    output: true
    permalink: /en/chapters/:name/

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 
